project:
  type: website
  
execute:
    freeze: auto

website:
  title: "You Can Begin Again"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: tenets.qmd
        text: Tenets
        
      - href: datavisualization.qmd
        text: Data Analysis
        
      - href: metadata.qmd
        text: Metadata

format:
  html:
    theme:
      - cosmo
      - style.scss
    #toc: true

