project:
  type: website

website:
  title: "You Can Begin Again: A Trans Archive on Video Game Avatar Creation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - new-page.qmd
      - about.qmd

format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true

editor: visual

