---
title: "Data Visualization"
execute:
  echo: false
---

```{r}
#| message: false
library(tidyverse)
data <- data.frame(
    group = c("He/Him", "She/Her", "They/Them", "He/They","She/They", "Any", "Neopronouns"),
    value = c(7, 3, 4, 3, 2, 1, 1)
)
```
```{r}
#| caption: "Distribution of Submitter Pronouns"
#| fig-alt: |
#|    This is a pie chart of the distribution of the pronouns
#|    of those who submitted to the archive.
pride_colors <- c(
  "Any"         = "#FF6130", 
  "He/Him"      = "#FF8847",
  "He/They"     = "#FFFF4D",
  "Neopronouns" = "#34F487",
  "She/Her"     = "#8F93FF",
  "She/They"    = "#D17BF9",
  "They/Them"   = "#FF69B4"
)

ggplot(data, aes(x = "", y = value, fill = group)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  scale_fill_manual(values = pride_colors) +
  theme_void() +
  labs(title = "Pronouns of Archive Participants" ,
        fill = "Pronouns") +
  geom_text(aes(label = paste0(round(value / sum(value) * 100), "%")),
            position = position_stack(vjust = 0.5))

```
```{r}
install.packages(c("ggalluvial"))
library(ggalluvial)
library(ggplot2)
library(dplyr)
```
```{r}
pronouns <- read_csv("data-raw/submissionimg-original.csv")

counts <- pronouns |>
  count(submitter_pronoun, avatar_pronouns) |>
  filter(!is.na(submitter_pronoun), !is.na(avatar_pronouns))
  
```

```{r}
ggplot(data = pronouns,
       aes(axis1 = submitter_pronoun, 
           axis2 = avatar_pronouns, 
           y = n)) +
geom_alluvium(aes(fill = submitter_pronoun)) +
geom_stratum() +
  geom_text(stat = "stratum",
           aes(label = after_stat(stratum))) +
scale_x_discrete(limits = c("submitter_pronoun", "avatar_pronouns"),
                  expand = c(0.1, 0.)) +
   labs(title = "Personal vs. Avatar Pronouns" ,
        y= counts, fill = "Pronouns")
  theme_void()

colnames(pronouns)
counts
```

            
            