---
title: "Archiving Transgender Worldmaking and Identity Performance in Video Games"
---

Searching for an outlet, many trans people find themselves drawn to video games as a form of escape from the threat of transphobic vitriol and gender-policing in the real world. The avatars that they make then become critical avenues of research for the ways in which they can assist in the exploration of gender identity.Through an intermingling of Judith Butler’s idea of performative gender in *Gender Trouble*, Sarah Ahmend’s *Queer Phenomenology*, and Uri Miller’s *Embodied Avatars*, this project understands the act of playing video games with a self-made avatar as a co-creationary performance of the self, in which trans gamers utilize their player characters to begin again.

This website hosts a variety of visualizations for the data attached to the submissions contained within the digital archive [*You Can Begin Again*](https://isaaclriddle.github.io/youcanbeginagain/collection/). These visualizations provide an overview of the demographics and experiences represented within the archive's collection.

# Submit to the Archive!

You can also submit to the archive in a [survey here](https://virginiatech.questionpro.com/youcanbeginagaindigitalarchivesubmissions). 
